#ifndef CONSTANT
#define CONSTANT

// MLP/MLPM
#define SUCCESS_INIT 0
#define ERR_INIT 1
#define SUCCESS_DINIT 0
#define ERR_DINIT 1
#define SUCCESS_INIT_WEIGHTS 0
#define ERR_INIT_WEIGHTS 1
#define SUCCESS_UPDATE_WEIGHTS 0
#define ERR_UPDATE_WEIGHTS 1
#define SUCCESS_CREATE_ARCHITECTURE 0
#define ERR_CREATE_ARCHITECTURE 1
#define SUCCESS_INIT_DATA 0
#define ERR_INIT_DATA 1

// MLPL
#define SUCCESS_CREATE_AUXS 0
#define ERR_CREATE_AUXS 1

// HMLPL
#define NO_CHANGE 10000

#endif